# Question 1
## Program to cyclically rotate an array by one in Python.

** Examples: ** <br />
** Input:  arr[] = {1, 2, 3, 4, 5} ** <br />
**  Output: arr[] = {5, 1, 2, 3, 4} ** <br />

In [5]:
l=input().rstrip().split()
n=int(input('Enter The rotation Value.'))
print(l[n:]+l[:n])

1 2 3 4 5
Enter The rotation Value.1
['2', '3', '4', '5', '1']


# Question 2
## Program to add two 3*3 matrix by user of every values.


In [7]:
import numpy as np
rows=int(input('Enter Rows. '))
columns=int(input('Enter Columns. '))
m1=list()
m2=list()
for i in range(0,rows*columns):
    n=int(input())
    m1.append(n)
    
for i in range(0,rows*columns):
    n=int(input())
    m2.append(n)
matrix1=np.array([m1]).reshape([3,3])
matrix2=np.array([m2]).reshape([3,3]);print('\n')
print("matrix1: ",matrix1);print('\n')
print("matrix2: ",matrix2);print('\n')
print('Addition: ',matrix1+matrix2);print('\n')
print('Subtraction: ',matrix1-matrix2);print('\n')
print('Subtraction: ',matrix1-matrix2);print('\n')
print('Division: ',matrix1/matrix2)
for i in matrix1:
    print(i)
for i in matrix1:
    print(i[0])

Enter Rows. 3
Enter Columns. 3
1
2
3
4
5
6
7
8
9
11
22
33
44
55
66
77
88
99


matrix1:  [[1 2 3]
 [4 5 6]
 [7 8 9]]


matrix2:  [[11 22 33]
 [44 55 66]
 [77 88 99]]


Addition:  [[ 12  24  36]
 [ 48  60  72]
 [ 84  96 108]]


Subtraction:  [[-10 -20 -30]
 [-40 -50 -60]
 [-70 -80 -90]]


Subtraction:  [[-10 -20 -30]
 [-40 -50 -60]
 [-70 -80 -90]]


Division:  [[0.09090909 0.09090909 0.09090909]
 [0.09090909 0.09090909 0.09090909]
 [0.09090909 0.09090909 0.09090909]]
[1 2 3]
[4 5 6]
[7 8 9]
1
4
7


# Question 3
## Program to find transpose and inverse of one 3*3 matrix by user of every values.

In [12]:
import numpy as np
rows=int(input('Enter Rows. '))
columns=int(input('Enter Columns. '))
m1=list()
for i in range(0,rows*columns):
    n=int(input())
    m1.append(n)
matrix1=np.matrix([m1]).reshape([3,3])
print(matrix1)
print('Inverse: ',matrix1.getI())
print('Transpose: ',matrix1.getT())

Enter Rows. 3
Enter Columns. 3
1
22
34
21
4
76
98
23
23
[[ 1 22 34]
 [21  4 76]
 [98 23 23]]
Inverse:  [[-0.0107068   0.00178447  0.00993095]
 [ 0.04503194 -0.02139421  0.00412496]
 [ 0.00058836  0.01379083 -0.00296118]]
Transpose:  [[ 1 21 98]
 [22  4 23]
 [34 76 23]]


# Question 4
## Create two matrix of 3*3 patter without numpy and perform add,sub,mul and div operation?

In [3]:
rows=int(input('Number of Rows: '))
columns=int(input('Number of Columns: '))
matrix1=[[[] for i in range(rows)] for i in range(columns)]
addition=[[[] for i in range(rows)] for i in range(columns)]
subtraction=[[[] for i in range(rows)] for i in range(columns)]
division=[[[] for i in range(rows)] for i in range(columns)]
print("Please Enter Elements of Matrix A: ")
for i in range(columns):
  for j in range(rows):
    number=int(input()) 
    matrix1[i][j]=number
print('matrix1: ',matrix1)
matrix2=[[[] for i in range(rows)] for i in range(columns)]
print("Please Enter Elements of Matrix B: ")
for i in range(columns):
  for j in range(rows):
    number=int(input()) 
    matrix2[i][j]=number
print('matrix2: ',matrix2)
for i in range(columns):
  for j in range(rows): 
    addition[i][j]=matrix1[i][j]+matrix2[i][j]
for i in range(columns):
  for j in range(rows): 
    subtraction[i][j]=abs(matrix1[i][j]-matrix2[i][j])
print('Addition: ',addition)
print('Subtraction: ',subtraction)
multiplication=[[0,0,0],[0,0,0],[0,0,0]]
#iterating through the rows of matrix1
for i in range(0,len(matrix1)):
  #iterating through the rows of matrix2
  for j in range(0,len(matrix2)):
    for k in range(0,len(matrix2)):
      multiplication[i][j]+=matrix1[i][k]*matrix2[k][i]
print("multiplication: ",multiplication)
for i in range(columns):
  for j in range(rows): 
    division[i][j]=matrix1[i][j]/matrix2[i][j]
print("division: ",division)

Number of Rows: 3
Number of Columns: 3
Please Enter Elements of Matrix A: 
1
2
3
4
5
6
7
8
9
matrix1:  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Please Enter Elements of Matrix B: 
11
22
33
44
55
66
77
88
99
matrix2:  [[11, 22, 33], [44, 55, 66], [77, 88, 99]]
Addition:  [[12, 24, 36], [48, 60, 72], [84, 96, 108]]
Subtraction:  [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
multiplication:  [[330, 330, 330], [891, 891, 891], [1650, 1650, 1650]]
division:  [[0.09090909090909091, 0.09090909090909091, 0.09090909090909091], [0.09090909090909091, 0.09090909090909091, 0.09090909090909091], [0.09090909090909091, 0.09090909090909091, 0.09090909090909091]]


# Question 4
## Total number of ones in a N*N matrix?

In [5]:
l=[[1,1,1,1,1],
[1,1,1,1,1], 
[1,1,0,1,1], 
[1,1,1,1,1],
[1,1,1,1,1]]
count=0
for i in range(0,len(l[0])):
    for j in range(0,len(l[0])):
        if l[i][j]==1:
            count+=1
        else:
            pass
print(count)


24


# Question 5
## find all subarrays whose average is great than given value of a given array?

In [7]:
l=[1,2,3,4,5]
n=int(input())
ll=[]
for i in l:
    ll.append(i)
    avg=sum(ll)/len(ll)
    if avg>n:
        print(ll)
    else:
        pass

print(ll) 
   


2
[1, 2, 3, 4]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


# Question 6
## Find all the sublists of a list?

In [9]:
l=list(map(int,input().split()))
subsets = []
for i in range(0, len(l)+1):
    #print(i)
    temp = [list(x) for x in itertools.combinations(l, i)]
    #print(temp)
    subsets.extend(temp)
print(subsets)

1 2 3 4 5
[[], [1], [2], [3], [4], [5], [1, 2], [1, 3], [1, 4], [1, 5], [2, 3], [2, 4], [2, 5], [3, 4], [3, 5], [4, 5], [1, 2, 3], [1, 2, 4], [1, 2, 5], [1, 3, 4], [1, 3, 5], [1, 4, 5], [2, 3, 4], [2, 3, 5], [2, 4, 5], [3, 4, 5], [1, 2, 3, 4], [1, 2, 3, 5], [1, 2, 4, 5], [1, 3, 4, 5], [2, 3, 4, 5], [1, 2, 3, 4, 5]]


# Question 7
## Find all the sublists of a list without using itertools?


In [5]:
def subsets(s):
    #base case
    if len(s) == 0:
        return [[]]
    # the input set is not empty, divide and conquer!
    h, t = s[0], s[1:];print('h: ',h);print('t: ',t)
    ss = subsets(t);print('ss: ',ss)
    ss1 = [([h] + n) for n in ss];print('ss1: ',ss1);print('yes')
    print('ss+ss1: ',ss+ss1)
    return ss+ss1
l=list(map(int,input().split())) 
print (subsets(l))

1 2 3
h:  1
t:  [2, 3]
h:  2
t:  [3]
h:  3
t:  []
ss:  [[]]
ss1:  [[3]]
yes
ss+ss1:  [[], [3]]
ss:  [[], [3]]
ss1:  [[2], [2, 3]]
yes
ss+ss1:  [[], [3], [2], [2, 3]]
ss:  [[], [3], [2], [2, 3]]
ss1:  [[1], [1, 3], [1, 2], [1, 2, 3]]
yes
ss+ss1:  [[], [3], [2], [2, 3], [1], [1, 3], [1, 2], [1, 2, 3]]
[[], [3], [2], [2, 3], [1], [1, 3], [1, 2], [1, 2, 3]]


# Question 8
## Find all the permutation of a list?

In [1]:
from itertools import permutations
l=[1,2,3,4]
print(list(permutations(l)))

[(1, 2, 3, 4), (1, 2, 4, 3), (1, 3, 2, 4), (1, 3, 4, 2), (1, 4, 2, 3), (1, 4, 3, 2), (2, 1, 3, 4), (2, 1, 4, 3), (2, 3, 1, 4), (2, 3, 4, 1), (2, 4, 1, 3), (2, 4, 3, 1), (3, 1, 2, 4), (3, 1, 4, 2), (3, 2, 1, 4), (3, 2, 4, 1), (3, 4, 1, 2), (3, 4, 2, 1), (4, 1, 2, 3), (4, 1, 3, 2), (4, 2, 1, 3), (4, 2, 3, 1), (4, 3, 1, 2), (4, 3, 2, 1)]


# Question 9
## Create a function that accepts a string argument and returns an array of strings, which are shifted versions of the argument string.

## Sample Input: "Hello"

## Sample Output: ["elloH", "lloHe", "loHel", "oHell", "Hello"]  

In [8]:
def indexing(l):
  return l[1:]+l[0]
def combinations(s):
  result=[]
  new_string=s
  for i in range(0,len(s)):
    #print(i)
    new_string=indexing(new_string)
    #print(new_string)
    result.append(new_string)
  return result

s=input('Enter Your String: ')
if len(s)==0:
  print('empty string')
else:
  print(combinations(s))

Enter Your String: hello
['elloh', 'llohe', 'lohel', 'ohell', 'hello']


# Question 10
## Prime or not?

In [21]:
n=int(input())
if n<=1:
    print('Neither Prime not composite')
else:
    for i in range(2,n):
        if (n%i)!=0:
            print('Prime')
            break;
        else:
            print('Not Prime')
            break;

4
Not Prime


# Question 11.
## Smallest subarray with sum greater than a given value?

In [31]:
import itertools
l=list(map(int,input().split()))
sorted(l)
value=int(input())
final=[]
for i in range(0,len(l)):
    for j in list(itertools.combinations(l,i)):
        final.append(j)
print(final);print('\n')
for i in final:
    if sum(i)>value:
        print(i)
        print(len(i))
        break;
    else:
        continue;


1 2 3 4 5
6
[(), (1,), (2,), (3,), (4,), (5,), (1, 2), (1, 3), (1, 4), (1, 5), (2, 3), (2, 4), (2, 5), (3, 4), (3, 5), (4, 5), (1, 2, 3), (1, 2, 4), (1, 2, 5), (1, 3, 4), (1, 3, 5), (1, 4, 5), (2, 3, 4), (2, 3, 5), (2, 4, 5), (3, 4, 5), (1, 2, 3, 4), (1, 2, 3, 5), (1, 2, 4, 5), (1, 3, 4, 5), (2, 3, 4, 5)]


(2, 5)
2


# Questions 12.
## Prime in a interval?

In [15]:
lower = int(input("Enter lower range: "))
upper = int(input("Enter upper range: "))
 
for num in range(lower,upper + 1):
   # prime numbers are greater than 1
   if num > 1:
       for i in range(2,num):
           if (num % i) == 0:
               break
       else:
           print(num)

Enter lower range: 900
Enter upper range: 1000
907
911
919
929
937
941
947
953
967
971
977
983
991
997


# Question 13.
## Take a string as input and then return the length of string without repetition.

In [1]:
n=input()
l=[]
for i in n:
    if i in l:
        pass
    else:
        l.append(i)
print(len(l))

abccd
4


## Alternative to question 13

In [2]:
n=input()
print(len(set(n)))

abccd
4


# Question - 14
## **Python Program to Change case of input string.**

In [3]:
s=input()
if (s.lower()):
    print(s.upper())
else:
    print(s.lower())

da
DA


# Question - 15
## **Python Program to find total number of each element of an array less than equal to all elements in other array.**

In [ ]:
def Find_Out(nums,maxes):
    Final_Out=[]
    for i in nums:
        count=0
        for j in maxes:
            if(i<=j):
                count+=0
            else:
                pass
        Final_Out.append(count)
    return Final_Out    

if __name__=="__main__":
    nums=[1,2,3,4]
    maxes=[2,4]
    print(Find_Out(nums,maxes))

# Question - 16
## **Python Program to make a complete sentence i.e first letter to be capital and sentence should be formed based on the length of each word and full stop in the end.**

In [1]:
if __name__=="__main__":
    s="india is a bautiful country"
    

# Question - 17
## **Given two integer number n and d. The task is to find the number between 0 to n which contain the specific digit d.**

In [2]:
n=int(input())
d=int(input())
l=[x for x in range(0,n)]
if(d in l):
    print('Present')
else:
    print('Absent')

20
4
Present


# Question - 18
## **Python Program to check whether all the digits of a number are sorted or not?**

In [2]:
n=int(input())
l=list()
for i in str(n):
    l.append(int(i))
#way-1
if(all(l[i] <= l[i+1] for i in range(len(l)-1))=='True'):
    print('Digits of a number are sorted')
else:
    print('Digits of a number are not sorted')

#way-2
m=[]
for i in range(0,len(l)-1):
    if(l[i]<l[i+1]):
        m.append(1)
    else:
        m.append(0)
        
if 0 in m:
    print('not sorted')
else:
    print('sorted')

1234
Digits of a number are not sorted
sorted


# Question - 18
## **Sum of all the digits in the integer.**

In [10]:
#simple way
n=int(input("Enter the number"))
print(sum([int(i) for i in str(n)]))

Enter the number1234
10


In [7]:
#hard way
def Sum(n):
    c=0
    while(n>0):
        x=n%10
        c=c+x
        n=n//10
    return c
    
    
if __name__=="__main__":
    n=int(input("Enter the integer"))
    m=Sum(n)
    print('The Sum of the digits in a list are: ',m)

Enter the integer1234
The Sum of the digits in a list are:  10


# **Question-19**
* ## **Convert a integer input into a list?**

In [2]:
#simple way
n=int(input("Enter the integer: "))
print('The list is: ',[int(i) for i in str(n)])

Enter the integer: 1234
The list is:  [1, 2, 3, 4]


In [6]:
#hard way
def Split(n):
    final=[]
    while(n>0):
        final.append(n%10)
        n=n//10
    
    return final[::-1]
if __name__=="__main__":
    n=int(input("Enter the integer"))
    m=Split(n)
    print('The list is: ',m)

Enter the integer1234
The list is:  [1, 2, 3, 4]


# **Question-20**
* ## **Minimize all the elements of an input array to zero?**

In [4]:
#hard way
def Move_Zero(x):
    x=x-1
    if x==0:
        return 0
    else:
        Move_Zero(x)
        
def Normalize(n):
    output=[]
    for i in n:
        if i==0:
            output.append(0)
        else:
            Move_Zero(i)
            output.append(0)
    return output

if __name__=="__main__":
    n=list(map(int,input().rstrip().split()))
    m=Normalize(n)
    print(m)

1 2 3 4
[0, 0, 0, 0]


In [2]:
#simple way
n=list(map(int,input().rstrip().split()))
out=[]
for i in n:
    if i==0:
        out.append(i)
    else:
        out.append(0)
print(out)

1 2 3 4
[0, 0, 0, 0]


# **Question-21**
* ## **Number of moves required to normalize all the elements of a array to 1?**

In [5]:
def Increment(x):
  x=x+1
  return x

def Decrement(y):
  y=y-1
  return y

def Normalize(n):
  c=0
  for i in n:
    if i==1:
      pass
    elif i<1:
      c=c+1
      Increment(i)
      if i==1:
        pass
      else:
        c=c+1
        Increment(i)
    else:
      c=c+1
      Decrement(i)
      if i==1:
        pass
      else:
        c=c+1
        Decrement(i)
  return c
  

if __name__=="__main__":
    n=list(map(int,input().rstrip().split()))
    m=Normalize(n)
    print(m)

1 2 3 4
6


# Question-22
## **Pattern-1?**

In [12]:
def Pattern(rows):
    for i in range(0,rows):
        for j in range(0,i+1):
            print("* ",end="")
        print('\r') #carriage return

if __name__=="__main__":
    rows=int(input("Enter the number of rows: "))
    Pattern(rows)

Enter the number of rows: 5
* 
* * 
* * * 
* * * * 
* * * * * 


# Question-23
## **Pattern-2?**