# **Modular Programming.**
* Modular programming is a software design technique, which is based on the general principal of modular design. Modular design is an approach which has been proven as indispensable in engineering even long before the first computers. 

* Modular design means that a complex system is broken down into smaller parts or components, i.e. modules. These components can be independently created and tested. In many cases, they can be even used in other systems as well. 

* There is hardly any product nowadays, which doesn't heavily rely on modularisation, like cars, mobile phones. Computers belong to those products which are modularised to the utmost. 

* So, what's a must for the hardware is an unavoidable necessity for the software running on the computers. 

## **Importing Topics.**
* importing modules.
* Designing and writing modules.

every file, which has the file extension .py and consists of proper Python code, can be seen or is a module! There is no special syntax required to make such a file a module. A module can contain arbitrary objects, for example files, classes or attributes. All those objects can be accessed after an import. 

* Now i'll show you some important modules.

### **Math Module.**
#### **List of Functions in Python Math Module.**
1. **Function	Description**
2. ceil(x) - Returns the smallest integer greater than or equal to x.
3. copysign(x, y) - Returns x with the sign of y
4. fabs(x) - Returns the absolute value of x
5. factorial(x) - Returns the factorial of x
6. floor(x) - Returns the largest integer less than or equal to x
7. fmod(x, y) - Returns the remainder when x is divided by y
8. frexp(x) - Returns the mantissa and exponent of x as the pair (m, e)
9. fsum(iterable) - Returns an accurate floating point sum of values in the iterable
10. isfinite(x) - Returns True if x is neither an infinity nor a NaN (Not a Number)
11. isinf(x) - Returns True if x is a positive or negative infinity
12. isnan(x) - Returns True if x is a NaN
13. ldexp(x, i) - Returns x * (2**i)
14. modf(x) -	Returns the fractional and integer parts of x
15. trunc(x) - Returns the truncated integer value of x
16. exp(x) - Returns e**x
17. expm1(x) - Returns e**x - 1
18. log(x[, base]) - Returns the logarithm of x to the base (defaults to e)
19. log1p(x) - Returns the natural logarithm of 1+x
20. log2(x) - Returns the base-2 logarithm of x
21. log10(x) - Returns the base-10 logarithm of x
22. pow(x, y) - Returns x raised to the power y
23. sqrt(x) - Returns the square root of x
24. acos(x) - Returns the arc cosine of x
25. asin(x) - Returns the arc sine of x
26. atan(x) - Returns the arc tangent of x
27. atan2(y, x) - Returns atan(y / x)
28. cos(x) - Returns the cosine of x
29. hypot(x, y) - Returns the Euclidean norm, sqrt(x*x + y*y)
30. sin(x) - Returns the sine of x
31. tan(x) - Returns the tangent of x
32. degrees(x) - Converts angle x from radians to degrees
33. radians(x) - Converts angle x from degrees to radians
34. acosh(x) - Returns the inverse hyperbolic cosine of x
35. asinh(x) - Returns the inverse hyperbolic sine of x
36. atanh(x) - Returns the inverse hyperbolic tangent of x
37. cosh(x) - Returns the hyperbolic cosine of x
38. sinh(x) - Returns the hyperbolic cosine of x
39. tanh(x) - Returns the hyperbolic tangent of x
40. erf(x) - Returns the error function at x
41. erfc(x) - Returns the complementary error function at x
42. gamma(x) - Returns the Gamma function at x
43. lgamma(x) - Returns the natural logarithm of the absolute value of the Gamma function at x
44. pi - Mathematical constant, the ratio of circumference of a circle to it's diameter (3.14159...)
45. e - mathematical constant e (2.71828...)

In [1]:
import math

In [9]:
math

<module 'math' from '/home/dammonoit/anaconda3/lib/python3.6/lib-dynload/math.cpython-36m-x86_64-linux-gnu.so'>

In [13]:
print(math.sqrt(2))             # square root of 2
print(math.radians(180))        # convert degrees to radians

1.4142135623730951
3.141592653589793


In [2]:
math.pi

3.141592653589793

In [3]:
math.cos(math.pi/2)

6.123233995736766e-17

In [2]:
math.sin(1)

0.8414709848078965

In [5]:
math.e

2.718281828459045

Its possible to import more than one module in one import statement. In this case the module names are separated by commas

In [5]:
import math, random

If only certain objects of a module are needed, we can import only those:

In [6]:
from math import sin, pi

Instead of explicitly importing certain objects from a module, it's also possible to import everything in the namespace of the importing module. This can be achieved by using an asterisk in the import

In [7]:
from math import *
print(sin(3))

0.1411200080598672


* It's not recommended to use the asterisk notation in an import statement, except when working in the interactive Python shell. One reason is that the origin of a name can be quite obscure, because it can't be seen from which module it might have been imported.

* Another way to shrink the typing effort consists in renaming a namespace. A good example for this is the numpy module. You will hardly find an example or a tutorial, in which they will import this module with the statement

In [8]:
#let's write dip into random module for sometime
import random
print(random.randint(1,3))  #it'll choose a number between 1 and 3
print(random.randint(1,1000))

2
213


In [10]:
random

<module 'random' from '/home/dammonoit/anaconda3/lib/python3.6/random.py'>

In [12]:
presidents = ['trump', 'romney', 'reagon']
print('presidents: ',presidents)
print('random.choice(presidents): ',random.choice(presidents))
print('random.sample(presidents,2): ',random.sample(presidents,2))
print('random.shuffle(presidents): ',random.shuffle(presidents))
print('presidents: ',presidents)

presidents:  ['trump', 'romney', 'reagon']
random.choice(presidents):  romney
random.sample(presidents,2):  ['trump', 'romney']
random.shuffle(presidents):  None
presidents:  ['trump', 'reagon', 'romney']


### **Time Module.**

In [14]:
import time
print(time.sleep(1))   # wait one second
print(time.time())     # return time in seconds since beginning of the year 1970
print(time.strftime('%d.%m.%Y %H:%M:%S'))  # format current time nicely

None
1547750941.6962624
18.01.2019 00:19:01


In [10]:
import numpy as np
print(np.diag([3, 11, 7, 9]))
np.e

[[ 3  0  0  0]
 [ 0 11  0  0]
 [ 0  0  7  0]
 [ 0  0  0  9]]


2.718281828459045

### **Itertools Modules.**
* Python itertools module is very useful in creating efficient iterators. 
* In almost every program you write with any programming language, one of the task which is usually always present is Iteration. 
* Traversing sequence of objects and manipulating them is very common.



In [6]:
from itertools import *

In [11]:
l=list(chain([1,2,3],['a','b','c','d'])) #chain function adds two sequences with each other of any type
ll=list(chain((1,2,3),['a','b','c','d'])) 
print('l: ',l)
print('ll: ',ll)

l:  [1, 2, 3, 'a', 'b', 'c', 'd']
ll:  [1, 2, 3, 'a', 'b', 'c', 'd']


In [12]:
#but list/string/tuples can add strings with + operation but not with other datatypes i.e tuples.
[1,2,3]+('a','b')

TypeError: can only concatenate list (not "tuple") to list

### **combination function in itertools.**
* If items in sequence are sorted, then combination will be sorted as well.
* If items in sequence are unique, then combination data will not contain any duplicate combination.

In [22]:
list(combinations('ABC',2))

[('A', 'B'), ('A', 'C'), ('B', 'C')]

In [23]:
list(combinations([1,2,3,4],3))

[(1, 2, 3), (1, 2, 4), (1, 3, 4), (2, 3, 4)]

In [24]:
list(combinations_with_replacement([1,2,3,4],3))

[(1, 1, 1),
 (1, 1, 2),
 (1, 1, 3),
 (1, 1, 4),
 (1, 2, 2),
 (1, 2, 3),
 (1, 2, 4),
 (1, 3, 3),
 (1, 3, 4),
 (1, 4, 4),
 (2, 2, 2),
 (2, 2, 3),
 (2, 2, 4),
 (2, 3, 3),
 (2, 3, 4),
 (2, 4, 4),
 (3, 3, 3),
 (3, 3, 4),
 (3, 4, 4),
 (4, 4, 4)]

In [25]:
#let's see an example
from itertools import *
l=[1,2,3]
m=[]
for i in range(len(l)+1):
  n=[tuple(x) for x in combinations(l,i)]
  m.append(n)
print(m)

[[()], [(1,), (2,), (3,)], [(1, 2), (1, 3), (2, 3)], [(1, 2, 3)]]


### **Permutation function in itertools.**

In [27]:
list(permutations('ABC'))

[('A', 'B', 'C'),
 ('A', 'C', 'B'),
 ('B', 'A', 'C'),
 ('B', 'C', 'A'),
 ('C', 'A', 'B'),
 ('C', 'B', 'A')]

In [28]:
list(permutations('ABC',2))

[('A', 'B'), ('A', 'C'), ('B', 'A'), ('B', 'C'), ('C', 'A'), ('C', 'B')]

In [29]:
#let's see an example
from itertools import *
l=[1,2,3]
m=[]
for i in range(len(l)+1):
  n=[tuple(x) for x in permutations(l,i)]
  m.append(n)
print(m)

[[()], [(1,), (2,), (3,)], [(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)], [(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]]


## **Collections Module.**
* The Collections module implements high-performance container datatypes (beyond the built-in types list, dict and tuple) and contains many useful data structures that you can use to store information in memory.

### **Counter in collections**
* A Counter is a container that tracks how many times equivalent values are added. 
* 'Import collections' makes the stuff in collections available as:
 collections.something
* Counter supports three forms of initialization. 

In [30]:
import collections
from collections import Counter

In [31]:
print(collections.Counter(['a', 'b', 'c', 'a', 'b', 'b']))
print(collections.Counter({'a':2, 'b':3, 'c':1}))
print(collections.Counter(a=2, b=3, c=1))

Counter({'b': 3, 'a': 2, 'c': 1})
Counter({'b': 3, 'a': 2, 'c': 1})
Counter({'b': 3, 'a': 2, 'c': 1})


### **Create and Update Counters**
* An empty Counter can be constructed with no arguments and populated via the 
 update() method.

In [32]:
c=collections.Counter()
c

Counter()

In [33]:
c.update("asdf")
c

Counter({'a': 1, 'd': 1, 'f': 1, 's': 1})

In [34]:
c.update(['a','b','d','s'])
c

Counter({'a': 2, 'b': 1, 'd': 2, 'f': 1, 's': 2})

In [35]:
c.update({'a':2,'b':4})
c

Counter({'a': 4, 'b': 5, 'd': 2, 'f': 1, 's': 2})

### **Accessing Counters.**
* Once a Counter is populated, its values can be retrieved using the counter object in similar way as dictionary.

In [36]:
for i,j in c.items():
    print(i,j)
    

a 4
s 2
d 2
f 1
b 5


In [37]:
c.items()

dict_items([('a', 4), ('s', 2), ('d', 2), ('f', 1), ('b', 5)])

In [38]:
c.keys()

dict_keys(['a', 's', 'd', 'f', 'b'])

In [39]:
c.values()

dict_values([4, 2, 2, 1, 5])