## **Python Numpy**
* The package is known for a very useful data structure called the NumPy array. 
* NumPy also allows Python developers to quickly perform a wide variety of numerical computations.

### **What is NumPy?**
* NumPy is a Python library for scientific computing. NumPy stand for Numerical Python. Here is the official description of the library from its website:

* “NumPy is the fundamental package for scientific computing with Python. It contains among other things:

    * a powerful N-dimensional array object
    * sophisticated (broadcasting) functions
    * tools for integrating C/C++ and Fortran code
    * useful linear algebra, Fourier transform, and random number capabilities
* Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

* NumPy is licensed under the BSD license, enabling reuse with few restrictions.”

* NumPy is such an important Python library that there are other libraries (including pandas) that are built entirely on NumPy.

### **The Main Benefit of NumPy**
* The main benefit of NumPy is that it allows for extremely fast data generation and handling. 
* NumPy has its own built-in data structure called an **array** which is similar to the normal Python list, but can store and operate on data much more efficiently.

### **What We Will Learn About NumPy?**
* Advanced Python practitioners will spend much more time working with pandas than they spend working with NumPy. 
* Still, given that pandas is built on NumPy, it is important to understand the most important aspects of the NumPy library.

* Over the next several sections, we will cover the following information about the NumPy library:

    * NumPy Arrays
    * NumPy Indexing and Assignment
    * NumPy Methods and Operations
    
### **NumPy Arrays**
* NumPy arrays are the main way to store data using the NumPy library. They are similar to normal lists in Python, but have the advantage of being faster and having more built-in methods.

* NumPy arrays are created by calling the array() method from the NumPy library. Within the method, you should pass in a list.

* An example of a basic NumPy array is shown below. Note that while I run the import numpy as np statement at the start of this code block, it will be excluded from the other code blocks in this section for brevity’s sake.

In [1]:
import numpy as np

sample_list = [1, 2, 3]

np.array(sample_list)

array([1, 2, 3])

* The **array()** wrapper indicates that this is no longer a normal Python list. Instead, it is a NumPy array.

### **The Two Different Types of NumPy Arrays**
* There are two different types of NumPy arrays: **vectors and matrices**.

* **Vectors** are **one-dimensional** NumPy arrays, and look like this:

In [2]:
my_vector = np.array(['this', 'is', 'a', 'vector'])
my_vector

array(['this', 'is', 'a', 'vector'], dtype='<U6')

* Matrices are two-dimensional arrays and are created by passing a list of lists into the **np.array()** method. 
* An example is below.

In [3]:
my_matrix = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]

np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

* You can also expand NumPy arrays to deal with three-, four-, five-, six- or higher-dimensional arrays, but they are rare and largely outside the scope of this course (after all, this is a course on Python programming, not linear algebra).

### **NumPy Arrays: Built-In Methods**
* NumPy arrays come with a number of useful built-in methods. We will spend the rest of this section discussing these methods in detail.

### **How To Get A Range Of Numbers in Python Using NumPy?**
* NumPy has a useful method called arange that takes in two numbers and gives you an array of integers that are **greater than or equal to (>=) the first number and less than (<) the second number**.

* An example of the arange method is below.

In [4]:
np.arange(0,5)

#Returns array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

* You can also include a third variable in the arange method that provides a **step-size** for the function to return. Passing in **2** as the third variable will return every 2nd number in the range, passing in 5 as the third variable will return every 5th number in the range, and so on.

* An example of using the third variable in the arange method is below.

In [5]:
np.arange(1,11,2)

#Returns array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

### **How To Generates Ones and Zeros in Python Using NumPy?**
* While programming, you will from time to time need to create arrays of **ones or zeros**. NumPy has built-in methods that allow you to do either of these.

* We can create arrays of zeros using NumPy’s **zeros method**. You pass in the number of integers you’d like to create as the argument of the function. An example is below.

In [12]:
np.zeros(4)

#Returns array([0, 0, 0, 0])

array([0., 0., 0., 0.])

* You can also do something similar using **three-dimensional** arrays. For example, **np.zeros(5, 5)** creates a **5x5** matrix that contains all zeros.

* We can create arrays of ones using a similar method named **ones**. An example is below.

In [10]:
np.ones(5)

#Returns array([1, 1, 1, 1, 1])

array([1., 1., 1., 1., 1.])

In [13]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.zeros([5,5],dtype="float")

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones([5,5],dtype="float")

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### **How To Evenly Divide A Range Of Numbers In Python Using NumPy?**
* There are many situations in which you have a **range** of numbers and you would like to **equally divide** that range of numbers into intervals. 
* NumPy’s **linspace method** is designed to solve this problem. linspace takes in three arguments:

    * The start of the interval
    * The end of the interval
    * The number of subintervals that you’d like the interval to be divided into

In [17]:
np.linspace(0, 1, 10)

#Returns array([0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### **How To Create An Identity Matrix In Python Using NumPy?**
* Anyone who has studied linear algebra will be familiar with the concept of an **‘identity matrix’**, which is a **square matrix whose diagonal values are all 1**. NumPy has a built-in function that takes in one argument for building identity matrices. The function is **eye.**

* Examples are below:

In [20]:
print(np.eye(1),"\n")

#Returns a 1x1 identity matrix

print(np.eye(2),"\n") 

#Returns a 2x2 identity matrix

print(np.eye(50),"\n")

#Returns a 50x50 identity matrix

[[1.]] 

[[1. 0.]
 [0. 1.]] 

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]] 



### **How To Create Random Numbers in Python Using NumPy?**
* NumPy has a number of methods built-in that allow you to create arrays of random numbers. 
* Each of these methods starts with random. 
* A few examples are below:

In [23]:
#np.random.rand(sample_size)
np.random.rand(5)

#Returns a sample of random numbers between 0 and 1.

#Sample size can either be one integer (for a one-dimensional array) or two integers separated by commas (for a two-dimensional array).





array([0.22902452, 0.46426105, 0.8882411 , 0.73108086, 0.5853537 ])

In [24]:
#np.random.randn(sample_size)
np.random.randn(5)
#Returns a sample of random numbers between 0 and 1, following the normal distribution.

#Sample size can either be one integer (for a one-dimensional array) or two integers separated by commas (for a two-dimensional array).

array([-2.00418236,  0.76809455, -0.5176424 , -0.92817779, -0.33696383])

In [25]:
#np.random.randint(low, high, sample_size)
np.random.randint(2, 10, 5)
#Returns a sample of integers that are greater than or equal to 'low' and less than 'high'

array([5, 5, 9, 5, 2])

### **How To Reshape NumPy Arrays?**
* It is very common to take an array with **certain dimensions** and transform that array into a different shape. For example, you might have a **one-dimensional array with 10 elements and want to switch it to a 2x5 two-dimensional array**.

* An example is below:

In [26]:
arr = np.array([0,1,2,3,4,5])

arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

* **Note** that in order to use the **reshape** method, the **original** array must have the **same number** of elements as the array that you’re trying to reshape it into.

* If you’re curious about the current **shape** of a NumPy array, you can determine its shape using **NumPy’s shape attribute**. Using our previous **arr** variable structure, an example of how to call the shape attribute is below:

In [28]:
arr = np.array([0,1,2,3,4,5])

print(arr.shape,"\n")

#Returns (6,) - note that there is no second element since it is a one-dimensional array

arr = arr.reshape(2,3)

arr.shape

#Returns (2,3)

(6,) 



(2, 3)

In [29]:
#You can also combine the reshape method with the shape attribute on one line like this:
arr.reshape(2,3).shape

#Returns (2,3)

(2, 3)

### **How To Find The Maximum and Minimum Value Of A NumPy Array?**
* To conclude this section, let’s learn about four useful methods for identifying the **maximum and minimum** values within a NumPy array. We’ll be working with this array:

In [35]:
simple_array = [1, 2, 3, 4]
n=np.array(simple_array)
n

array([1, 2, 3, 4])

In [36]:
n.max()

#Returns 4

4

* We can also use the **argmax method** to find the index of the maximum value within a NumPy array. This is useful for when you want to find the **location** of the maximum value but you do not necessarily care what its value is.

* An example is below.

In [38]:
n.argmax()

#Returns 3

3

* Similarly, we can use the **min** and **argmin methods** to find the value and index of the minimum value within a NumPy array.

In [40]:
n.min()

#Returns 1

1

In [42]:
n.argmin()

#Returns 0

0